phrase = "Nour Alaa"
print(phrase.lower())
print("*********************************")
print(phrase.isupper())
print("*********************************")
print(phrase.upper().isupper())
print("*********************************")
print(len(phrase))
print("*********************************")
print(phrase[0])
print("*********************************")
print(phrase[8])
print("*********************************")
print(phrase.index("A"))
print("*********************************")
print(phrase.replace("Nour","Yousr"))
print("*********************************")
print(phrase + " is cool")